import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";



export const metadata: Metadata = {
  title: "Collections",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <div className="w-[90%] mx-auto my-6 font-inter">
          <Header />
            {children}
        </div>
        <Footer />
    </html>
  );
}
