import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@/public/styles/font.css'
import '@/public/styles/index.css'
import '@/public/styles/tailwind.css'
import ReduxProvider from "@/features/ReduxProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>   
        <body className={inter.className}>
            {children}
          </body>
    </ReduxProvider>
    </html>
  );
}

// Test