import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@/public/styles/font.css'
import '@/public/styles/index.css'
import '@/public/styles/tailwind.css'
import Header from "@/components/Header";
import Footer from "@/components/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Risidio app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={inter.className}>
        <div className="w-[90%] mx-auto my-6 font-inter">
          <Header />
            {children}
        </div>
        <Footer />
          </body>
    </html>
  );
}
