import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";



export const metadata: Metadata = {
  title: "Wallet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <section className="bg-[#E6E9F2] h-[100vh]">
        <div className="w-[90%] mx-auto mb-6 pt-6 font-inter">
          <Header />
        </div>
            {children}
        </section>
    </html>
  );
}
